# VIREON Repository Cleanup & Organization Script
# ===============================================
# Standardizes project structure for Symbeon Labs

$ErrorActionPreference = "Stop"
$ROOT = "c:\Users\João\Desktop\PROJETOS\03_AI_AGENTS\VIREON"

Write-Host "=" * 60 -ForegroundColor Cyan
Write-Host "VIREON REPO CLEANUP & ORGANIZATION" -ForegroundColor Cyan
Write-Host "=" * 60 -ForegroundColor Cyan

# 1. Create standard directories if missing
$dirs = @("docs", "scripts", "legacy", "legacy/web", "legacy/api")
foreach ($d in $dirs) {
    if (-not (Test-Path "$ROOT\$d")) {
        New-Item -ItemType Directory -Force -Path "$ROOT\$d" | Out-Null
        Write-Host "  ✅ Created directory: $d" -ForegroundColor Green
    }
}

# 2. Clean specific IDE/Warp files (Delete)
Write-Host "`n[1/5] Removing IDE-specific clutter..." -ForegroundColor Yellow
$to_delete = @(
    "warp_mcp_config.json",
    "warp_mcp_config_minimal.json",
    "warp_mcp_config_npm.json",
    "warp_mcp_vireon_config.json",
    "styles-warp.css",
    "index-warp.html",
    ".metrics_history.json",
    "session_complete.txt",
    "task_mesh_summary_*.json",
    "migration_*.log",
    "consciousness_initialization_*.log"
)

foreach ($f in $to_delete) {
    if (Test-Path "$ROOT\$f") {
        Remove-Item "$ROOT\$f" -Force
        Write-Host "  🗑️ Deleted: $f" -ForegroundColor DarkGray
    }
}

if (Test-Path "$ROOT\WARP_RULES") { Remove-Item "$ROOT\WARP_RULES" -Recurse -Force; Write-Host "  🗑️ Deleted: WARP_RULES" -ForegroundColor DarkGray }
if (Test-Path "$ROOT\WARP_SAGE_INTEGRATION") { Remove-Item "$ROOT\WARP_SAGE_INTEGRATION" -Recurse -Force; Write-Host "  🗑️ Deleted: WARP_SAGE_INTEGRATION" -ForegroundColor DarkGray }


# 3. Move Scripts
Write-Host "`n[2/5] Organizing scripts..." -ForegroundColor Yellow
Get-ChildItem "$ROOT" -Filter "*.ps1" | Move-Item -Destination "$ROOT\scripts" -Force
Get-ChildItem "$ROOT" -Filter "*.sh" | Move-Item -Destination "$ROOT\scripts" -Force
Write-Host "  ✅ Moved .ps1 and .sh files to /scripts" -ForegroundColor Green

# 4. Move Documentation
Write-Host "`n[3/5] Organizing documentation..." -ForegroundColor Yellow
$docs_to_keep_root = @("README.md", "Checklists.md", "LICENSE-TIERS.md", "RELEASE_NOTES.md", "IP_PROTECTION_CHECKLIST.md", "CONTRIBUTING.md", "CODE_OF_CONDUCT.md", "CHANGELOG.md", "AUTHORS", "LICENSE", "EAP_ROADMAP.md")

Get-ChildItem "$ROOT" -Filter "*.md" | Where-Object { $docs_to_keep_root -notcontains $_.Name } | Move-Item -Destination "$ROOT\docs" -Force
Write-Host "  ✅ Moved .md files to /docs (kept critical root files)" -ForegroundColor Green


# 5. Move Legacy Web/API code
Write-Host "`n[4/5] Archiving legacy code..." -ForegroundColor Yellow
$legacy_web = @("index.html", "index-*.html", "styles.css", "favicon.svg", "vite.config.ts", "vireon_logo.svg")
foreach ($f in $legacy_web) {
    if (Test-Path "$ROOT\$f") { Move-Item "$ROOT\$f" -Destination "$ROOT\legacy\web" -Force }
}

$legacy_api = @("vireon_api.py", "vireon_ui.py", "vireon_cli_enhanced.py", "vireon_minimal.py", "init_vireon.py", "init_vireon_safe.py", "models.py", "vireon.py", "vireon_interface.py")
foreach ($f in $legacy_api) {
    if (Test-Path "$ROOT\$f") { Move-Item "$ROOT\$f" -Destination "$ROOT\legacy\api" -Force }
}
Write-Host "  ✅ Moved legacy HTML/Python files to /legacy" -ForegroundColor Green


# 6. Generate DocSync Index (Simulation)
Write-Host "`n[5/5] Generating Documentation Index..." -ForegroundColor Yellow
$index_content = @"
# 📚 VIREON Documentation Index

## 🚀 Getting Started
- [Quick Start](../README.md#quick-start)
- [Installation Guide](./QUICKSTART.md)

## 🏗️ Architecture
- [System Architecture](./ARCHITECTURE_UNIFIED.md)
- [Vireon Core Blueprint](./VIREON_BLUEPRINT.md)
- [Universal Governance](./VIREON_UNIVERSAL_GOVERNANCE.md)

## 🗺️ Roadmap & Strategy
- [EAP Roadmap](../EAP_ROADMAP.md)
- [Development Strategy](./DEVELOPMENT_STRATEGY.md)
- [Market Research](./MARKET_RESEARCH.md)

## 🔐 Compatibility & Migration
- [Migration Guide](./MIGRATION.md)
- [Legacy Architecture](./ARCHITECTURE.md)

---
*Generated by DocSync*
"@

Set-Content -Path "$ROOT\docs\INDEX.md" -Value $index_content
Write-Host "  ✅ Created docs/INDEX.md" -ForegroundColor Green

Write-Host "`n"
Write-Host "=" * 60 -ForegroundColor Green
Write-Host "✅ REPO CLEANUP COMPLETE" -ForegroundColor Green
Write-Host "=" * 60 -ForegroundColor Green
