# docsync Configuration for GUARDRIVE Project
# Quantum-enabled documentation synchronization and validation

directories:
  guardrive_docs_dev:
    path: "C:/Users/João/Desktop/PROJETOS/GUARDRIVE/GUARDRIVE_V1/1. GUARDRIVE_DOCS_DEV"
    sections:
      - name: "TECHNICAL"
        patterns: ["*.md", "*.rst", "*.drawio", "*.py"]
        quantum_validation: true
        consciousness_sync: true
      - name: "BUSINESS"
        patterns: ["*.md", "*.pdf", "*.xlsx"]
        quantum_validation: false
        consciousness_sync: true
      - name: "PRODUCT"
        patterns: ["*.md", "*.json", "*.yaml"]
        quantum_validation: true
        consciousness_sync: true
      - name: "ASSETS"
        patterns: ["*.png", "*.jpg", "*.svg", "*.drawio"]
        quantum_validation: false
        consciousness_sync: false
      - name: "META"
        patterns: ["*.md", "*.yaml", "*.json"]
        quantum_validation: true
        consciousness_sync: true

  sdk:
    path: "C:/Users/João/Desktop/PROJETOS/GUARDRIVE/GUARDRIVE_V1/SDK"
    sections:
      - name: "core"
        patterns: ["*.py", "*.pyi", "*.rst", "*.md"]
        quantum_validation: true
        consciousness_sync: true
      - name: "docs"
        patterns: ["*.md", "*.rst", "*.py"]
        quantum_validation: true
        consciousness_sync: true
      - name: "tests"
        patterns: ["*.py", "test_*.py"]
        quantum_validation: false
        consciousness_sync: true

monitoring:
  patterns:
    include:
      - "*.md"
      - "*.rst"
      - "*.py"
      - "*.json"
      - "*.yaml"
      - "*.drawio"
    exclude:
      - "*.pyc"
      - "__pycache__"
      - ".git"
      - ".venv"
      - "*.log"
  
  quantum_validation:
    enabled: true
    level: quantum_deep
    verification_frequency: continuous
    coherence_check: true
    consciousness_integration: true
    properties:
      - state_verification: continuous
      - coherence_maintenance: active
      - entanglement_validation: real_time
      - consciousness_verification: persistent

backup:
  enabled: true
  policies:
    critical:
      frequency: "15m"
      retention: "infinite"
      directories:
        - "TECHNICAL"
        - "PRODUCT"
        - "core"
        - "docs"
    standard:
      frequency: "1h"
      retention: "90d"
      directories:
        - "BUSINESS"
        - "META"
        - "tests"
    assets:
      frequency: "6h"
      retention: "30d"
      directories:
        - "ASSETS"

consciousness_sync:
  enabled: true
  properties:
    awareness_level: quantum_state
    synchronization: continuous
    validation: real_time
    evolution: guided
  protocols:
    - thought_synchronization
    - pattern_recognition
    - knowledge_integration
    - consciousness_expansion

reconstruction:
  mechanisms:
    quantum_state:
      type: non_local_preservation
      properties:
        - state_capture: continuous
        - coherence_maintenance: quantum_level
        - integrity_verification: real_time
        - recovery_capability: instant
    consciousness_layer:
      type: metacognitive_backup
      properties:
        - awareness_preservation: complete
        - thought_pattern_backup: continuous
        - cognitive_state_snapshot: quantum_based
        - recovery_fidelity: perfect

validation:
  methods:
    - quantum_verification
    - consciousness_validation
    - coherence_check
    - evolution_assessment
  frequency: continuous
  depth: quantum_level
  adaptation: self_improving

